<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="generator" content="pandoc">
  <title>Exceptions</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="reveal.js/css/reset.css">
  <link rel="stylesheet" href="reveal.js/css/reveal.css">
  <style>
      code{white-space: pre-wrap;}
      span.smallcaps{font-variant: small-caps;}
      span.underline{text-decoration: underline;}
      div.column{display: inline-block; vertical-align: top; width: 50%;}
  </style>
    <link rel="stylesheet" href="reveal.js/css/theme/blackschool.css" id="theme">
    <!-- Printing and PDF exports -->
  <script>
    var link = document.createElement( 'link' );
    link.rel = 'stylesheet';
    link.type = 'text/css';
    link.href = window.location.search.match( /print-pdf/gi ) ? 'reveal.js/css/print/pdf.css' : 'reveal.js/css/print/paper.css';
    document.getElementsByTagName( 'head' )[0].appendChild( link );
  </script>
  <!--[if lt IE 9]>
  <script src="reveal.js/lib/js/html5shiv.js"></script>
  <![endif]-->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" />
</head>
<body>
  <div class="reveal">
    <div class="slides">

<section id="title-slide">
  <h1>Exceptions</h1>
    
    <p>
    <h4></h4>
    </p>
  </section>


<section><section id="intro" class="title-slide slide level1"><h1>Intro</h1></section><section id="what-is-an-exception" class="title-slide slide level2"><h2>What Is an Exception?</h2><p>The Java uses exceptions to handle errors and other exceptional events.</p>
<p>The term exception is shorthand for <q>exceptional event</q>.</p>
<blockquote>
<p>Definition: An exception is an event, which occurs during the execution of a program, that disrupts the normal flow of the programâ€™s instructions.</p>
</blockquote>
<p><a href="https://docs.oracle.com/javase/tutorial/essential/exceptions/definition.html" target="_blank">[reference]</a></p></section><section id="call-stack" class="title-slide slide level2"><h2>Call stack</h2><div style="text-align: center;">
<img alt="" src="https://docs.oracle.com/javase/tutorial/figures/essential/exceptions-callstack.gif" style="width:50%" />
</div></section><section id="searching-the-call-stack-for-the-exception-handler" class="title-slide slide level2"><h2>Searching the call stack for the exception handler</h2><div style="text-align: center;">
<img alt="" src="https://docs.oracle.com/javase/tutorial/figures/essential/exceptions-errorOccurs.gif" style="width:50%" />
</div></section><section id="the-catch-or-specify-requirement" class="title-slide slide level2"><h2>The Catch or Specify Requirement</h2><p>Code that throws exceptions must be enclosed by either:</p>
<ul>
<li><p>A <code>try</code> statement that catches the exception.</p></li>
<li><p>A method that specifies that it <code>throws</code> the exception.</p></li>
</ul>
<p><strong>Code that fails to honor the Catch or Specify Requirement will not compile.</strong></p>
<p>Not all exceptions are subject to the Catch or Specify Requirement.</p></section><section id="a-try-statement-that-catches-the-exception." class="title-slide slide level2"><h2>A <code>try</code> statement that catches the exception.</h2><p>The <code>try</code> statement must provide a handler for the exception.</p></section><section id="a-method-that-specifies-that-it-throws-the-exception." class="title-slide slide level2"><h2>A method that specifies that it <code>throws</code> the exception.</h2><p>The method must provide a <code>throws</code> clause that lists the exception.</p></section></section>
<section><section id="kinds-of-exceptions" class="title-slide slide level1"><h1>Kinds of Exceptions</h1><p><img alt="" src="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Java_exception_classes.svg/1920px-Java_exception_classes.svg.png" style="width:50%" /></p>
<p><small>CC-AT-SA https://commons.wikimedia.org/wiki/File:Java_exception_classes.svg</small></p></section><section id="exceptions-checked-exceptions" class="title-slide slide level2"><h2>Exceptions (checked exceptions)</h2><p>These are exceptional conditions that a well-written application should anticipate and recover from. <!--
For example, suppose an application prompts a user for an input file name, then opens the file by passing the name to the constructor for java.io.FileReader. 
Normally, the user provides the name of an existing, readable file, so the construction of the FileReader object succeeds, and the execution of the application proceeds normally. 
But sometimes the user supplies the name of a nonexistent file, and the constructor throws java.io.FileNotFoundException. 

A well-written program will catch this exception and notify the user of the mistake, possibly prompting for a corrected file name.
--></p>
<p>Checked exceptions are subject to the Catch or Specify Requirement.</p>
<p>All exceptions are checked exceptions, except for those indicated by <code>Error</code>, <code>RuntimeException</code>, and their subclasses.</p></section><section id="errors" class="title-slide slide level2"><h2>Errors</h2><p>These are exceptional conditions that are external to the application, and that the application usually cannot anticipate or recover from.</p>
<p>Errors are not subject to the Catch or Specify Requirement. Errors are those exceptions indicated by Error and its subclasses.</p></section><section id="runtime-exceptions" class="title-slide slide level2"><h2>Runtime exceptions</h2><p>These are exceptional conditions that are internal to the application, and that the application usually cannot anticipate or recover from.</p>
<p>These usually indicate programming bugs, such as logic errors or improper use of an API. The application can catch this exception, but it probably makes more sense to eliminate the bug that caused the exception to occur.</p>
<p>Runtime exceptions are not subject to the Catch or Specify Requirement. Runtime exceptions are those indicated by RuntimeException and its subclasses.</p></section></section>
<section><section id="catching-and-handling-exceptions" class="title-slide slide level1"><h1>Catching and Handling Exceptions</h1></section><section id="try" class="title-slide slide level2"><h2><code>try</code></h2><p>Separation of concerns:</p>
<ul>
<li><p>logic that might throw the exception</p></li>
<li><p>logic that handle given exception</p></li>
</ul>
<pre><code>try {
  ... // protected code
} catch ( &lt;exception-type&gt; &lt;identifier&gt; ) {
  ... // catch block
}</code></pre></section><section id="catch" class="title-slide slide level2"><h2><code>catch</code></h2><p>You associate exception handlers with a try block by providing one or more catch blocks directly after the try block. No code can be between the end of the try block and the beginning of the first catch block.</p>
<pre><code>try {

} catch (ExceptionType name) {

} catch (ExceptionType name) {

}</code></pre>
<p><a href="https://docs.oracle.com/javase/tutorial/essential/exceptions/catch.html" target="_blank">[reference]</a></p></section><section id="finally" class="title-slide slide level2"><h2><code>finally</code></h2><pre><code>try {

} catch (ExceptionType name) {

} finally {

}</code></pre>
<p>The finally block always executes when the try block exits. This ensures that the finally block is executed even if an unexpected exception occurs.</p>
<p><a href="https://docs.oracle.com/javase/tutorial/essential/exceptions/finally.html" target="_blank">[reference]</a></p></section><section id="try-with-resources" class="title-slide slide level2"><h2>Try with resources</h2><p>The close() method of an <code>java.lang.AutoCloseable</code> object is called automatically when exiting a try-with-resources block for which the object has been declared in the resource specification header.</p>
<pre><code>try (BufferedReader br = new BufferedReader(new FileReader(path))) {
    return br.readLine();
}</code></pre></section></section>
<section><section id="throwing" class="title-slide slide level1"><h1>Throwing</h1></section><section id="specifying-the-exceptions-thrown-by-a-method" class="title-slide slide level2"><h2>Specifying the Exceptions Thrown by a Method</h2><p><code>void myMethod() throws MyException { ... }</code></p>
<p><a href="https://docs.oracle.com/javase/tutorial/essential/exceptions/declaring.html" target="_blank">[reference]</a></p></section><section id="how-to-throw-exceptions" class="title-slide slide level2"><h2>How to Throw Exceptions?</h2><p><code>throw new MyException()</code></p>
<p><a href="https://docs.oracle.com/javase/tutorial/essential/exceptions/throwing.html" target="_blank">[reference]</a></p></section></section>
<section id="the-end" class="title-slide slide level1"><h1>The end</h1></section>
    </div>
  </div>
    <script src="reveal.js/js/reveal.js"></script>

      <script>

          // Full list of configuration options available at:
          // https://github.com/hakimel/reveal.js#configuration
          Reveal.initialize({
              // Push each slide change to the browser history
              history: true,
              slideNumber: true,

              // Optional reveal.js plugins
              dependencies: [
                  { src: 'reveal.js/lib/js/classList.js', condition: function() { return !document.body.classList; } },
                  { src: 'reveal.js/plugin/zoom-js/zoom.js', async: true },
                  { src: 'reveal.js/plugin/notes/notes.js', async: true }
              ]
          });
      </script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-41987357-2"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'UA-41987357-2');
</script>
</body>
</html>